apiVersion: v1
data:
  .dockerconfigjson: <container registry config>
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: https://quay.io
  name: container-registry-secret
  namespace: cicd
type: kubernetes.io/dockerconfigjson
